### ISSUE TITLE
Listing of project data

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/open.ribose.com#1]
* RNP
  * Site: rnpgp.com
  * Software:
    * RNP https://github.com/riboseinc/rnp
    * RNP Ruby Bindings https://github.com/riboseinc/ruby-rnp
    * Homebrew formula for RNP https://github.com/riboseinc/homebrew-rnp
    * RNP Tools https://github.com/riboseinc/rnp-tools
    * RNP Python Bindings https://github.com/riboseinc/py-rnp
    * RNP Go Bindings https://github.com/riboseinc/go-rnp
  * Spec:
    * https://datatracker.ietf.org/doc/draft-openpgp-iana-registry-updates
    * https://datatracker.ietf.org/doc/draft-ribose-openpgp-sca

* Metanorma
  * Site: metanorma.com, asciiiso.com, asciirfc.com
  * Spec:
    * Metanorma StanDoc https://github.com/riboseinc/standoc-models
    * Metanorma IsoDoc https://github.com/riboseinc/isodoc-models
    * Metanorma CsdDoc https://github.com/riboseinc/csd
    * Metanorma GbDoc https://github.com/riboseinc/gbdoc
    * Metanorma RsdDoc https://github.com/riboseinc/rsd-models
    * Metanorma CsaDoc https://github.com/riboseinc/csad-models
    * Metanorma AsciiRFC Minimal Document https://github.com/riboseinc/rfc-asciirfc-minimal
    * Metanorma AsciiRFC Spec Source Document https://github.com/riboseinc/rfc-asciidoc-rfc
    * IETF AsciiRFC Spec Document https://datatracker.ietf.org/doc/draft-ribose-asciirfc
    * IETF AsciiRFC Sample Document: Camelot https://datatracker.ietf.org/doc/draft-camelot-holy-grenade/
    * AsciiRFC Source Document: Camelot https://github.com/riboseinc/rfc-camelot-holy-grenade
    * IETF AsciiRFC Sample Document: Divination API https://datatracker.ietf.org/doc/draft-divination-cfapi/
    * AsciiRFC Source Document: Divination API https://github.com/riboseinc/rfc-divination-cfapi
    * Metanorma AsciiISO Rice Document https://github.com/riboseinc/isodoc-rice
    * Metanorma AsciiGB Rice Document https://github.com/riboseinc/gbdoc-rice
  * Software:
    * Metanorma Ruby https://github.com/riboseinc/metanorma
    * Metanorma IsoDoc Ruby https://github.com/riboseinc/isodoc
    * Metanorma AsciiRFC https://github.com/riboseinc/asciidoctor-rfc
    * Metanorma AsciiISO https://github.com/riboseinc/asciidoctor-iso
    * Metanorma ISO HTML Styling https://github.com/riboseinc/isodoc-style
    * Metanorma AsciiCSD https://github.com/riboseinc/asciidoctor-csd
    * Metanorma CSD HTML Styling https://github.com/riboseinc/csd-style
    * Metanorma AsciiGB https://github.com/riboseinc/asciidoctor-gb
    * Metanorma GB HTML Styling https://github.com/riboseinc/gbdoc-style
    * Metanorma AsciiRSD https://github.com/riboseinc/asciidoctor-rsd
    * Metanorma RSD HTML Styling https://github.com/riboseinc/rsd-style
    * Metanorma AsciiCSAD https://github.com/riboseinc/asciidoctor-csadoc
    * Metanorma CSADoc HTML Styling https://github.com/riboseinc/csa-style
    * Metanorma HTML2Doc https://github.com/riboseinc/html2doc
    * ReverseAsciidoctor https://github.com/riboseinc/reverse_asciidoctor
    * MathML2AsciiMath https://github.com/riboseinc/mathml2asciimath

* Retrace
  * Site: pending
  * Software:
    * Retrace https://github.com/riboseinc/retrace
    * Homebrew formula for Retrace https://github.com/riboseinc/homebrew-retrace

* Relaton
  * Site: https://www.relaton.com
  * Software:
    * Relaton IsoBib Ruby https://github.com/riboseinc/isobib
    * Relaton IsoBibItem Ruby https://github.com/riboseinc/iso-bib-item
    * Relaton GbBib Ruby https://github.com/riboseinc/gbbib
  * Spec:
    * Relaton Ruby https://github.com/riboseinc/relaton
    * Relaton models https://github.com/riboseinc/bib-models
    * Relaton IsoBib models https://github.com/riboseinc/isodoc-models
    * Relaton GbBib models https://github.com/riboseinc/gbdoc
    * Relaton ISO 690 extension models https://github.com/riboseinc/iso690xml

* Riffol
  * Site: https://www.riffol.com
  * Software:
    * Riffol in Rust https://github.com/riboseinc/riffol

* Kaohi
  * Site: pending
  * Software:
    * Kaohi (Go) https://github.com/riboseinc/kaohi

* Multi-config (pending name change)
  * Site: pending
  * Software:
    * go-multiconfig in Go https://github.com/riboseinc/go-multiconfig
    * libmulticonfig in C https://github.com/riboseinc/libmulticonfig

* RVC
  * Site: pending
  * Software:
    * RVC https://github.com/riboseinc/rvc
    * Homebrew formula for RVC https://github.com/riboseinc/homebrew-rvc

* Ribose Open
  * Site: Ribose Open?
  * Software:
    * Ribose CLI https://github.com/riboseinc/ribose-cli
    * Ribose Ruby API https://github.com/riboseinc/ribose-ruby
    * Ribose JS API https://github.com/riboseinc/ribose-js

* Selagraph
  * Site: selagraph.com
  * Software:
    * Selagraph https://github.com/riboseinc/selagraph

**Comment by strogonoff** [comment]
Thanks @ronaldtse. For the optimal use of everyone’s time I’m going to do a sampling with RNP and a couple of Metanorma items for now.

Later for the rest we can consider establishing a routine that either builds the habit of project maintainers updating their sites (“push” mode) or designating a documentation/open relations person (“pull” mode), a good process would really help reduce overhead and prevent sites from going stale.

**Comment by strogonoff** [comment]
Created #2 and #3, this one being a not-an-issue is heading into wiki

**Comment by strogonoff** [comment]
https://github.com/riboseinc/open.ribose.com/wiki/Listing-of-open-projects

**Comment by ronaldtse** [comment]
@strogonoff 

I've updated this part in the Wiki:

* Nereon
  * Site: https://www.nereon.com
  * Spec:
    * Nereon and Nerelog models: https://github.com/riboseinc/event-configuration-models 
  * Software:
    * go-multiconfig in Go https://github.com/riboseinc/go-multiconfig
    * libmulticonfig in C https://github.com/riboseinc/libmulticonfig
