### ISSUE TITLE
Update project logos

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/open.ribose.com#13]
Update project logos for Metanorma and RNP, provided here:

https://github.com/riboseinc/open-design

**Comment by strogonoff** [comment]
@ronaldtse can we trigger a rebuild of the hub? Open Project framework would display each project’s logo as specified in their corresponding site assets after that.

**Comment by ronaldtse** [comment]
The trigger is automatic, I wonder if the build is failing. I know @ribose-jeffreylau is having trouble building the site?

**Comment by strogonoff** [comment]
This did not involve a commit in the hub repo, because logos are updated in the repos of respective projects. Hence I asked for manual build on hub site in this scenario. I’ll make a chore commit for this then.

**Comment by strogonoff** [comment]
If there is trouble building the site, feel free to file an issue with an error, maybe I’ve already dealt with it, or if not I’ll try to reproduce it in my environment and see. I imagine the troubling part would be the helpers gem as it contains the bulk of logic in Ruby. @ronaldtse @ribose-jeffreylau

**Comment by strogonoff** [comment]
Fresh logos should be pulled with https://github.com/riboseinc/open.ribose.com/commit/99f51ba274d4cb7a19684301e33e635bf3f53b6e

**Comment by ribose-jeffreylau** [comment]
@strogonoff Thanks.  Indeed the error is in the helper gem.  I've just posted an issue there.

https://github.com/riboseinc/jekyll-theme-open-project-helpers/issues/5
