### ISSUE TITLE
Production build faulty, not consistent with local build

### ISSUE THREAD

**Issue by strogonoff** [riboseinc/open.ribose.com#18]
Even if build & deployment complete correctly, hub site build fails to pull software, specs, posts from respective project sites.

It also fails to pull the logo for Cryptode, which was recently added. (Existing project logos remain—I’m not sure whether this means hub site manages to pull them as intended, or it’s just because hub build environment is not clean and has those logos left over from previous builds.)

Local build (bundle exec jekyll serve) works and seems to pull data from project sites as intended.

Perhaps there’s something with connectivity/networking on the machine where build happens during Travis CI?

**Comment by strogonoff** [comment]
Currently still a problem

<img width="1301" alt="Screen Shot 2019-04-05 at 9 09 20 AM" src="https://user-images.githubusercontent.com/292959/55597905-86c60480-5782-11e9-94f4-4720d531cd0c.png">

**Comment by ronaldtse** [comment]
@strogonoff any updates to this? The deployment script is exactly the same as the other ones...

**Comment by strogonoff** [comment]
I have no updates yet :(

**Comment by strogonoff** [comment]
Again, since it works locally the issue is clearly in the CI.

**Comment by strogonoff** [comment]
Note that for example Metanorma.com (builds properly) uses Travis-ci.org, while open.ribose.com gets successfully built on Travis-ci.com (since .org is not set up correctly) — #20

**Comment by strogonoff** [comment]
I seem to have reproduced the issue (or looks like it), ETA this weekend for open.ribose.com to be fixed.

**Comment by strogonoff** [comment]
Stop-gap measure implemented & production fixed, working on a proper fix.

**Comment by ronaldtse** [comment]
Thanks!

**Comment by strogonoff** [comment]
Proper fix implemented. It might’ve been a change in Jekyll behavior or something, but in the end the issue was fixable by altering helpers gem logic for reading project data. Apologies for occupying unnecessary cycles by barking at the wrong tree (CI).

Submodules still on the table in their separate issue. Problems with submodules that I intend to explore in a branch and possibly an experimental release of the Open Project theme:

1) As discussed with Ronald privately, the relationship between hub and project sites goes both ways. Hub site serves to provide some shared assets and configuration to project sites. It’s not possible to have a submodule loop, but this may be solvable by having another endpoint (repository or such) provide configuration details, and have all members of open project site network obtain configuration from there.

2) I haven’t mentioned it explicitly, but we may run into Git edge cases while having a huge submodule tree: hub site referring to project sites, each of which referring to multiple software packages (which, in turn, can also submodule other stuff). If we go with submodules, this complicated structure would be coded in repository, rather than being an ephemeral build-stage detail.
