### ISSUE TITLE
open.ribose.com gets build double, on both travis-ci.org and travis-ci.com

### ISSUE THREAD

**Issue by strogonoff** [riboseinc/open.ribose.com#20]
* on Travis “org” it fails due to missing variables in settings, and I get emailed on every failure: https://travis-ci.org/riboseinc/open.ribose.com
* on Travis “com” it succeeds (though with the error described in the currently pinned issue): https://travis-ci.com/riboseinc/open.ribose.com

To disable the “org” build, I tried going to https://travis-ci.org/organizations/riboseinc/repositories, but the toggles are disabled on my account.

**Comment by ronaldtse** [comment]
@strogonoff on "com" it succeeds: what's the error?

https://travis-ci.com/riboseinc/open.ribose.com

`Skipping a deployment with the s3 provider because this branch is not permitted: master` this line is normal, because we have two deployment targets, one for `master` and one for `staging`.
In the staging deployment, `master` does not match, and is hence not deployed to `staging`.

**Comment by ronaldtse** [comment]
P.S. "org" is old, I don't know where we can disable it.

**Comment by ronaldtse** [comment]
I just disabled it using your link. Thanks!

**Comment by strogonoff** [comment]
> What’s the error?

No error, succeeds but gets built incompletely as described in pinned issue and visible in prod. I’m investigating.

**Comment by strogonoff** [comment]
Downgrading theme didn’t help, thus so far it looks unrelated to data pulling logic in Open Project helpers or (since it’s the same as on other RO sites) the build script. Like something on Travis magically changed and it stopped working as intended.

If I can’t pinpoint the issue I might resort to submodules and we’ll have to bump submodule commits every now and then, or automate committing that change on CI step (which would be a bit complex because we’ll have to give CI environment commit rights).

**Comment by strogonoff** [comment]
> org is old

I thought it’s what they still use for free OSS builds, but not sure

**Comment by ronaldtse** [comment]
Nope, they’re migrating all to “.com”

**Comment by ronaldtse** [comment]
Even with sub modules we don’t need to make commits. Just run a command “git submodule update --init” before generating then they all get updated to the latest.

**Comment by strogonoff** [comment]
I see, good to know.

**Comment by strogonoff** [comment]
> Even with sub modules we don’t need to make commits. Just run a command “git submodule update --init” before generating then they all get updated to the latest.

The issue is that we need recursive sort of embedding, since project sites refer to their hub site (currently to avoid duplicating hub information such as logo all over the place), and hub site refers to its project sites. From my understanding, this sort of recursive submoduling is illegal under Git.

**Comment by strogonoff** [comment]
Marking this one as closed, since we no longer have duplicate builds going
