### ISSUE TITLE
Software, Specifications and Blog sections empty

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/open.ribose.com#27]
Somehow the Projects page works, but the rest don't.

Front page:
<img width="579" alt="Screen Shot 2020-05-31 at 1 08 31 PM" src="https://user-images.githubusercontent.com/11865/83344919-d466de80-a33f-11ea-82d3-3df27f0f0f44.png">

Projects:
<img width="603" alt="Screen Shot 2020-05-31 at 1 08 39 PM" src="https://user-images.githubusercontent.com/11865/83344922-d892fc00-a33f-11ea-8113-2b4d0df9c68d.png">

Software:
<img width="591" alt="Screen Shot 2020-05-31 at 1 08 47 PM" src="https://user-images.githubusercontent.com/11865/83344924-dd57b000-a33f-11ea-8551-a098cac00c0f.png">

Specifications:
<img width="578" alt="Screen Shot 2020-05-31 at 1 08 57 PM" src="https://user-images.githubusercontent.com/11865/83344929-e3e62780-a33f-11ea-86b1-fabca3b8ef30.png">

Blog:
<img width="594" alt="Screen Shot 2020-05-31 at 1 09 07 PM" src="https://user-images.githubusercontent.com/11865/83344932-e9dc0880-a33f-11ea-80c7-dd9a804e22cd.png">

**Comment by ronaldtse** [comment]
Ping @strogonoff can you help fix this? Thanks!

**Comment by strogonoff** [comment]
Confirmed locally, watching production build.

By the looks of it something changed in how (1) includes_dir gets inherited and (2) collection static files are output.

**Comment by strogonoff** [comment]
Persists (another issue prevents build, already located)
