### ISSUE TITLE
Broken links on the latest news section

### ISSUE THREAD

**Issue by abunashir** [riboseinc/open.ribose.com#30]
Hey there, we were going through the site today and noticed all the blog article links on the latest news section are broken - https://open.ribose.com, could we have someone to look into it?

That reminds me - one of my friend @mre is also working on an interesting project that checks all the links for your site, maybe that's something we could consider to add in our build pipeline? https://github.com/lycheeverse/lychee-action

//cc: @ronaldtse, @strogonoff

**Comment by ronaldtse** [comment]
@abunashir sorry for the late reply, we've always wanted to use a link checker but haven't had the time to integrate. Would be great if you could do that!

**Comment by abunashir** [comment]
@mre: is it something you could help us with please? 😉

**Comment by mre** [comment]
Sure. Created a pull request here: https://github.com/riboseinc/open.ribose.com/pull/32
