### ISSUE TITLE
Deploy open.ribose.com

### ISSUE THREAD

**Issue by strogonoff** [riboseinc/open.ribose.com#4]

**Comment by strogonoff** [comment]
@ronaldtse I think we’re on track to have this Ribose Open published before Monday, and with actual content (as opposed to sample/demo one)

**Comment by strogonoff** [comment]
@ronaldtse, are you working on Rakefile/Jenkinsfile as of now, or can I take over?

**Comment by ronaldtse** [comment]
@strogonoff I got carried away with other work. Would be great if you can take them over -- all we need is a Jenkinsfile for deployment. Thanks!

**Comment by ronaldtse** [comment]
P.S. The Jenkinsfile just needs to upload to the S3 bucket (as it is currently coded). Thanks!

**Comment by strogonoff** [comment]
Status: ETA pushed back a week. Working on updating the Rakefile in #8.

**Comment by strogonoff** [comment]
@ronaldtse Sorry, missed your message and done a bit of probably unnecessary work on Rakefile. Question: where do `s3Upload` and `cfInvalidate` commands come from in Jenkinsfile? (https://github.com/riboseinc/open.ribose.com/blob/master/Jenkinsfile#L37)

Is that something that needs implementing? Where is it implemented? I’m afraid I just don’t have a good enough picture of the overall infrastructure at this point.

**Comment by ronaldtse** [comment]
The `s3Upload` and `cfInvalidate` commands are given by the Pipeline AWS Plugin: https://plugins.jenkins.io/pipeline-aws

**Comment by strogonoff** [comment]
@ronaldtse 

Got a couple more questions:

1. Are environment variables like [`${env.HOST}`](https://github.com/riboseinc/open.ribose.com/blob/master/Jenkinsfile#L37) already set up on Jenkins side?
1. How do I test the Jenkinsfile on Ribose infrastructure?
1. If you have a general documentation of CI infrastructure somewhere, that’d help

**Comment by strogonoff** [comment]
The site has been functioning on test-open.ribose.com
