### ISSUE TITLE
Deprecate bundled Rakefile

### ISSUE THREAD

**Issue by strogonoff** [riboseinc/open.ribose.com#6]
It appears suboptimal that advanced build/deployment logic gets included in Open project/hub site codebases. Sites should only include content, anything beyond that is taken care of by `jekyll build` and resource provisioning by build/deployment/CI (e.g., a Terraform project).

Created https://github.com/riboseinc/jekyll-theme-open-hub/issues/9 to bundle an example Terraform project with the Open Project theme.

In context of Ribose Open operations, that Terraform project can become the one I mentioned in my recommendation in [Ribose Dev Ribose space conversation](https://www.ribose.com/#spaces/28bf5276-b686-45ad-8352-edcfa1195ac3/conversation/conversations/23a584a7-a2ba-400c-86a9-b90b99730a5d/messages/b28f82eb-e74f-4b7c-a92f-2c0626075ff1). It wouldn’t contain sensitive credentials or infrastructure specifics.

Once https://github.com/riboseinc/jekyll-theme-open-hub/issues/9 is done, we can migrate from Rakefile to that infrastructure. In meantime #4 can be taken care of with existing tools.

— Anton

**Comment by ronaldtse** [comment]
@strogonoff I fully agree. BTW @kwkwan will move this repo to a Travis CI deployment flow, I've just converted https://github.com/riboseinc/riffol.com to it.

**Comment by ronaldtse** [comment]
(P.S. it still uses the Rakefile :wink:)

**Comment by strogonoff** [comment]
Great news, with Travis there’s better visibility into CI failures too!

**Comment by strogonoff** [comment]
I think a Rakefile and even Jenkinsfile is a bit un-DRY and we could simplify adoption by bundling a deployment mechanism as part of our Open Project framework, but I am not sure how we can do this with CI too. Might close this ticket as won’t fix.

**Comment by ronaldtse** [comment]
@strogonoff agree, let's close this for now. Thanks!
